name: ⏰ Keep Alive

on:
  schedule:
    - cron: '0 12 1 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Keep repo active
        run: |
          git config user.name "Keep Alive Bot"
          git config user.email "keepalive@noreply.github.com"
          git commit --allow-empty -m "⏰ Keep alive $(date '+%Y-%m')"
          git push
